### ISSUE TITLE
Crash w/ Voxels Mod

### ISSUE THREAD

**Issue by WenXin20** [thebrightspark/SparksHammers#20] opened 2017-03-29 20:07 UTC
[Voxels](https://minecraft.curseforge.com/projects/voxels) v1.0.8
Spark's Hammers v1.6.3.1
Forge 1.10.2-2254
I got this crash after clicking on this mod's creative tab. No hammers were displaying in the tab before it crashed, only the hammer crafting table and other items.
[Crash Report](https://pastebin.com/hhsiqkyv)

**Comment by thebrightspark** [comment] 2017-03-29 23:23
Unfortunately I couldn't re-create this using the same mods.
Tbh, I think this is an issue with Voxels anyway, but since their code is not open source I can't even confirm that. There's nothing I can do over here, so I strongly suggest posting this on their issues and see what they say.

I'll close this issue for now, but we can re-open this if it's confirmed this is an issue in my mod.

**Closed as completed by thebrightspark** 2017-03-29 23:23 UTC
Labels: compatibility

**Comment by WenXin20** [comment] 2017-03-29 23:39
Ok, thanks
