### ISSUE TITLE
"Modded" Hammers disappeared in update

### ISSUE THREAD

**Issue by davqvist** [thebrightspark/SparksHammers#53] opened 2018-07-19 13:35 UTC
I just updated from 1.7.1 to 1.8.0 and all the "modded" hammers like Copper, Tin, Silver, Lead, etc. don't exist anymore. Is there anything I need to do to re-enable them? I couldn't find anything in the change log.

**Comment by thebrightspark** [comment] 2018-07-19 13:53
Hmm strange, it's possible I messed something up.
Can you try delete (or just move it if you want to keep any changes you may have made) your customTools.json and then open MC again?

**Comment by davqvist** [comment] 2018-07-19 14:15
I deleted it and restarted the pack, tools were still missing.

**Comment by thebrightspark** [comment] 2018-07-19 14:18
Interesting. Can you please list what mods you have installed and send my your logs for that restart right after you deleted the customTools.json?

**Comment by thebrightspark** [comment] 2018-07-19 14:21
Also, did the customTools.json re-create with all of those other modded materials in there?

**Comment by davqvist** [comment] 2018-07-19 14:21
It's my modpack Exoria (modlist: https://minecraft.curseforge.com/projects/exoria/relations/dependencies)
https://gist.github.com/davqvist/fde8b8c78997828ab71c40e6d7be7bd0

**Comment by davqvist** [comment] 2018-07-19 14:22
It did regenerate

**Comment by thebrightspark** [comment] 2018-07-19 14:29
Cool, yeah I can also see from the logs that the tools were generated:
[16:10:21] [main/INFO] [Spark's Hammers]: Spark's Hammers: Reading custom tools from json file...
[16:10:21] [main/INFO] [Spark's Hammers]: Spark's Hammers: Firing RegisterToolEvent for other mods
[16:10:21] [main/INFO] [Spark's Hammers]: Spark's Hammers: Collected 0 tools from other mods
[16:10:21] [main/INFO] [Spark's Hammers]: Spark's Hammers: Creating json file with 36 tools...
[16:10:21] [main/INFO] [Spark's Hammers]: Spark's Hammers: Finished creating json file

I'm not sure what the issue is... sounds like the items simply aren't being registered but I don't see how.
I'll have to take a look at this when I have some time, but a heads up that I won't be able to until Tuesday :( So unfortunately I recommend downgrading back to 1.7.1 until I can fix this if you want those other tools.

**Comment by Priderino** [comment] 2018-07-19 19:57
Also trying to modify the CustomTools file causes the game to crash:
Crashlog: https://paste.dimdev.org/opunepesul.mccrash
CustomTools: https://paste.dimdev.org/enicuyoles.json

**Comment by thebrightspark** [comment] 2018-07-19 20:29
Ah yeah the recipe for the Size Upgrade needs Stone Hammers, so since you removed that hammer, the recipe errors. As a work around for now, you either need to add the Stone Hammer back in or remove the Powered Hammer.

Please can put that in a new issue though? It's not related to this one at all and it'll help me keep track of these when I get round to fixing them.

**Comment by thebrightspark** [comment] 2018-07-23 23:49
Fixed in commit https://github.com/thebrightspark/SparksHammers/commit/747f2d655c8da66ceacc4fd90c75dd562b67e209

**Closed as completed by thebrightspark** 2018-07-23 23:49 UTC
