### ISSUE TITLE
Not a issue, just a warn to remove from latest.log

### ISSUE THREAD

**Issue by alxcool** [thebrightspark/SparksHammers#51] opened 2018-07-03 20:26 UTC
Almost forgot minimal info : 
1.12.2 singleplayer
forge 2705
sparkshammers-1.12.2-1.7.1
EnderIO-1.12.2-5.0.26
Note : I've forgot to check for latest version, so if required I will edit this file list!

[Spark's Hammers]: Spark's Hammers: Couldn't get enderio:blockCapBank for Powered Hammer recipe! Resorting to normal recipe. Please report this to mod author!

[16:06:58] [main/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `hammer_block`, expected `sparkshammers`. This could be a intended override, but in most cases indicates a broken mod.

And about the second line of code, If I understand it well, 1.12.2 have a function in less, in comparison to 1.11.2. So when we talk about substitution, one way to fix the problem, create this warning. I hope my shared link could solve this issue. Soon I hope being able to send a complete fix file for minor warn like this, but as for now I'm not confident enough about code writing!
http://www.minecraftforge.net/forum/topic/61332-1122-no-more-substitution-aliases/

Good luck and this issue could be closed as soon as you want to! ;)
https://pastebin.com/YyvJ8Tgp

**Comment by thebrightspark** [comment] 2018-07-03 23:51
Oh nice catch!
Don't worry, that is the latest version of the mod.

The first log won't be an issue in the next version. It's actually a feature I'd forgotten about but doesn't really play well with the new(ish) customTools JSON file, so I've removed these recipe overrides for the next version.

The second log is something I've not noticed before... Probably something I did accidentally :) I'll make sure to address this before the next version is released.

Thanks!

**Comment by thebrightspark** [comment] 2018-07-04 20:01
I don't see that second log in my testing at all... Although I noticed you have it _a lot_ for in the logs you sent, which makes me believe that a mod that you're using is actually causing that issue for all other mods.

I'll close this, but if you can prove that the issue is due to my mod, then I'll try look into it but I really can't see anything wrong with my mod.

**Closed as completed by thebrightspark** 2018-07-04 20:01 UTC
